---
output: 
  pdf_document:
    citation_package: natbib
    toc: false
    number_sections: false
    keep_tex: true
    fig_caption: true
    template: ../../Research/templates/gsingh-basic.tex
title: "Game Design Pitch"
subtitle: "Galloping Wheelbarrows"
subsubtitle: "Can you deliver the dirt on time?"

runhead: "Galloping Wheelbarrows"
author:
- name: Gurpreet Singh
  affiliation: CS4483 \#250674134
date: "`r format(Sys.time(), '%B %d, %Y')`"
geometry: margin=0.9in
fontsize: 12pt
indent: no
colorlinks: true
---

## Premise
The game will be an addictive 2D speed-based platform game and will focus on
fast moving action and racing. The characters is the game are different types
of wheelbarrows and the story revolves around delivering precious dirt to the
destination on time. The game will require fast reactions and button spamming to
win races. Single and multi-player game modes will be available.

## Player Motivation
The player will be driven to achieve the fastest record time on a map and beat
his peers in multi-player mode by mastering new techniques and reacting faster
to the changing map conditions. As the player progresses they will unlock new
maps but the basic movement techniques will remain the same. The player just
becomes better at incorporating them into their play style to move faster.

The story mode of the game provides a timed challenge for the user to complete 
and increases the number of different maps a player can play. The story is also
meant to be comedy so the player will have a good time discovering what will 
happen next.

## Genre
The genres for the game are speed-based, action, platformer and will be played
on the PC platform. Galloping Wheelbarrows will be following most conventional
game mechanics for these genres. One aspect that isn't seen in other
platformers is that it will be impossible to miss a platform, and instead of
having to aim for a platform, the user will have to adjust their direction of
travel to match where the next platform is going to maintain momentum.

For example, one platform could be leading the player in the right direction
but then theres a loop into a jump and the next platform leads left. If the
user doesn't change their direction from right to left, they will loss all
their speed upon landing on the next platform

## Gameplay

### Gamemodes
In single player mode the player will try to get to the end of the map in the
least amount of time and in multi-player mode the player can race against other
players. The game will be played on a map per map basis with a menu screen 
in between to switch between maps and progress in the story.

### Maps
A map will consist of a series of platforms going from the start of the race to
the end of a race. Some platforms may be reused but there will always be one
clear direction for the user to travel. Each platform will direct the player in
either the left or right direction. Each platform can also have special
qualities like speed increasing platforms, inclined/declined platforms, and
platforms that don't allow tricks on them.

### Player Controls
The player will use the left and right arrow keys to pick a direction to move
the player. Other controls include U to jump, E to flip right, O to flip left,
and A to do a spin. These controls will be re-bindable in the settings menu and
new controls may be added later in development to include a wider range of
tricks. When the player holds either left or right the character slowly
increases in speed the longer the key is being held and the visual model of
a wheelbarrow will show this by increasingly leaning forward the longer the key
is held.

### Playing a Round
In each round of the game the user (a wheelbarrow) will be placed in the center
of the screen and the round will begin with a countdown. When the countdown
ends the user will be allowed the move the character and begin racing from
platform to platform and doing tricks to gain speed.

Each time the character successfully lands a trick, it gains a boost in
momentum. Chaining multiple tricks together without messing up will allow for
the fastest traversal through the map. In order to achieve this the user will
have to know or predict the map correctly because tricks can be disrupted by
certain platforms or increase/decreases in elevation.

There is a stopwatch in the top right corner of the screen showing the player
how long they have taken to complete the map and if there are multiple laps or
not.

### Movement Tricks

The player can use the flip keys or spin key to do a trick while they are in
the air. In order to gain a momentum boost from the trick, the character has to
land at the correct angle. For example if the character is moving right, and
does a front flip, the wheelbarrow has to be leaning rightward to gain
a momentum boost. If the wheelbarrow is leaning backward the character will
bounce and lose speed.

## Competitive Analysis

Other games that operate with similar mechanics are Sonic the Hedgehog, Freedom
Planet and Uniracers. Uniracers is a direct competitor but is an old game that
has no chance of recreation. Freedom Planet and Sonic the Hedgehog are not the
same concept but target similar markets so they can also be considered
competition.

Sonic the Hedgehog popularized this play style but used it in more of
roleplaying fashion instead of racing. Freedom Planet expanded and improved
upon some of Sonic's best gameplay aspects but it remained fundamentally the
same in terms of gameplay. These games didn't utilize the concept of doing
tricks to gain more speed in the same way that Galloping Wheelbarrows will and
therefore they are fundamentally different.

A major pro for these games is their's impressive map design and level music.
Those qualities will be very difficult to beat. A major con is the lack of
advanced movement mechanics in both games. Galloping Wheelbarrows will be
adding lots of complexity to movement and therefore increase the skill ceiling.

Uniracers is a SNES game from 1994 that has similar movement mechanics as
Galloping Wheelbarrows but encountered a lawsuit from Pixar due to graphics and
therefore is no longer available to the mass audience. Although, the general
concept is similar, it has a very limited set of tricks and characters that
I would like to expand upon with Galloping Wheelbarrows. It also does not have
a story.

## Unique Selling Proposition (USP)

The concept of a fast paced wheelbarrow racing game has not been created yet
and I think there is a lot of potential to use this unusual combination to
appeal to gamers. The simple and unrestrictive game mechanics of Galloping
Wheelbarrows allows users to endlessly master and exploit the maps to traverse
them at insanely fast speeds.

This game will stand out from other retro games due to it's high skill ceiling 
caused by advanced movement mechanics and funny story to ease the player into
the gameplay.

## Story Synopsis

Galloping Wheelbarrows is not heavily based around the story therefore it takes
this opportunity to have a funny narrative before a map round starts. The
narrator takes the player through a story of how a boy needs to deliver
a wheelbarrow full of dirt to his father before nightfall. That boy has a magic
wheelbarrow that can do tricks and go very fast. Then a game round starts with
a wheelbarrow full of dirt and instead of the usual stopwatch, a timer is
started and the user must deliver the dirt before the timer goes to zero.
The main character is the wheelbarrow and his name is Martin. 

## Target Market

The target market for this game would be PC gamers who enjoy retro style games.
People who have played uniracers in their childhood would really enjoy this
game as a modern evolution of that concept with good graphics. The target
demographic would be people old enough to have played Uniracers on SNES but it
wouldn't be restricted to that because the game would be fun even if you didn't
recognize it's predecessor game. The game would aim to be ESRB rated E for
Everyone. 

## Target Platform

Galloping Wheelbarrows will be created primarily for the GNU/Linux platform and
if possible later expanded to Windows. It will aim to require very little
hardware requirements and use minimal dependencies to allow the most people to
play it without difficulty.

## Summary

In conclusion Galloping Wheelbarrows will be a game that makes many people
happy and endlessly challenge their quick thinking skills.
